# Numpy

Q: Why Numpy is Faster? <br/>

A: i) Because numpy uses fixed type. <br/>
In Numpy, 5 = 00000000 00000000 00000000 00000101 (Int32)
Whereas in list stores much more like size,reference count, object type, object value which has its own bit associated with it.

<b>So, its faster to read less bytes of memory</b>

ii) <b>No type checking</b> when iterating through memories

iii) Numpy uses <b>contiguous memory blocks</b>, while lists doesn't.
So, Effective Cache utilisation


In [2]:
import numpy as np

In [3]:
#initialisation of array
a = np.array([1,2,4])
print(a)

[1 2 4]


In [16]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
#get dimension
a.ndim

1

In [8]:
# get shape
b.shape

(3, 3)

In [9]:
# Get type
a.dtype

dtype('int64')

In [11]:
#specifying datatype
b = np.array([1,2,3], dtype='int16')
print(b)
b.dtype

[1 2 3]


dtype('int16')

In [14]:
#Get size
print(a.itemsize)
b.itemsize

8


2

In [15]:
# get total size
a.nbytes

24

<h2> Accessing/Changing specific elements,rows,elements etc

In [17]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
a.shape

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


(2, 7)

In [20]:
#getting specific element
a[1,5]

13

In [21]:
a[1,-2]

13

In [22]:
# getting specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
# getting specific column
a[:,0]

array([1, 8])

In [24]:
# [startindex : endindex : stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [26]:
#changing particular element
a[1,5] = 100
print(a)

[[  1   2   3   4   5   6   7]
 [  8   9  10  11  12 100  14]]


In [28]:
#changing particular row
a[0,:] = 20
print(a)
a[0,:] = [-1,-2,-3,-4,-5,-6,-7]
print(a)

[[ 20  20  20  20  20  20  20]
 [  8   9  10  11  12 100  14]]
[[ -1  -2  -3  -4  -5  -6  -7]
 [  8   9  10  11  12 100  14]]


In [30]:
#changing particular column
a[:,5] = [6,69]
print(a)

[[-1 -2 -3 -4 -5  6 -7]
 [ 8  9 10 11 12 69 14]]


<b>Leaving to play around

## Initializing Different types of Arrays

In [32]:
# All 0s matrix
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
# All 1s matrix
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [35]:
# Any other numbers
np.full((3,4) , 23)

array([[23, 23, 23, 23],
       [23, 23, 23, 23],
       [23, 23, 23, 23]])

In [37]:
#any other number
np.full_like(a , 41)

array([[41, 41, 41, 41, 41, 41, 41],
       [41, 41, 41, 41, 41, 41, 41]])

In [38]:
# Random decimal numbers
np.random.rand(2,3)

array([[0.32582831, 0.66899601, 0.27022346],
       [0.30749305, 0.57405804, 0.89355458]])

In [39]:
np.random.random_sample(a.shape)

array([[0.4165216 , 0.27216261, 0.67505537, 0.1849109 , 0.05639756,
        0.7498288 , 0.08161811],
       [0.97265587, 0.67693409, 0.03651363, 0.68660906, 0.28538733,
        0.6356863 , 0.76155835]])

In [48]:
# random Integer values
np.random.randint(10)

4

In [45]:
np.random.randint(100,size=(3,4))


array([[68, 43, 70,  8],
       [90, 58, 90, 84],
       [13,  7,  4, 51]])

In [47]:
# Identity Matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# repeat